import assets from "./images.js";

export const DATA = [
  {
    id: 100,
    title: "Restaurante 01",
    category: "Restaurante",
    tags: ["premium", "gastronomía", "business", "aventura"],
    src: {
      type: "image",
      jpg: assets.restaurant1,
      webp: assets.restaurant1Webp,
    },
    width: 1024,
    height: 768,
    views: 1331,
    createdAt: "2024-07-01",
  },
  {
    id: 101,
    title: "Destino 02",
    category: "Destino",
    tags: ["vista mar", "aventura", "romantico", "cultura"],
    src: {
      type: "image",
      jpg: assets.destination2,
      webp: assets.destination2Webp,
    },
    width: 1600,
    height: 1200,
    views: 529,
    createdAt: "2024-07-06",
  },
  {
    id: 102,
    title: "Restaurante 03",
    category: "Restaurante",
    tags: ["cultura", "aventura", "wellness", "premium"],
    src: {
      type: "image",
      jpg: assets.restaurant3,
      webp: assets.restaurant3Webp,
    },
    width: 1080,
    height: 1350,
    views: 524,
    createdAt: "2024-07-11",
  },
  {
    id: 103,
    title: "Restaurante 04",
    category: "Restaurante",
    tags: ["eco", "vista mar", "terraza"],
    src: {
      type: "image",
      jpg: assets.restaurant4,
      webp: assets.restaurant4Webp,
    },
    width: 1024,
    height: 768,
    views: 376,
    createdAt: "2024-07-16",
  },
  {
    id: 104,
    title: "Destino 05",
    category: "Destino",
    tags: ["vista mar", "romantico", "aventura"],
    src: {
      type: "image",
      jpg: assets.destination5,
      webp: assets.destination5Webp,
    },
    width: 1600,
    height: 1200,
    views: 1268,
    createdAt: "2024-07-21",
  },
  {
    id: 105,
    title: "Experiencias 06",
    category: "Experiencias",
    tags: ["eco", "business", "aventura"],
    src: {
      type: "video",
      mp4: assets.experience6Video,
      poster: assets.experience6Webp,
    },
    width: 1080,
    height: 1350,
    views: 1966,
    createdAt: "2024-07-26",
  },
  {
    id: 106,
    title: "Restaurante 07",
    category: "Restaurante",
    tags: ["vista mar", "premium"],
    src: {
      type: "image",
      jpg: assets.restaurant7,
      webp: assets.restaurant7Webp,
    },
    width: 1920,
    height: 1080,
    views: 1063,
    createdAt: "2024-07-31",
  },
  {
    id: 107,
    title: "Restaurante 08",
    category: "Restaurante",
    tags: ["wellness", "pet-friendly", "romantico", "eco"],
    src: {
      type: "image",
      jpg: assets.restaurant8,
      webp: assets.restaurant8Webp,
    },
    width: 1920,
    height: 1080,
    views: 1088,
    createdAt: "2024-08-05",
  },
  {
    id: 108,
    title: "Experiencias 09",
    category: "Experiencias",
    tags: ["cultura", "business", "wellness"],
    src: {
      type: "image",
      jpg: assets.experience9,
      webp: assets.experience9Webp,
    },
    width: 1024,
    height: 768,
    views: 1246,
    createdAt: "2024-08-10",
  },
  {
    id: 109,
    title: "Restaurante 10",
    category: "Restaurante",
    tags: ["vista mar", "romantico", "business", "premium"],
    src: {
      type: "video",
      mp4: assets.restaurant10Video,
      poster: assets.restaurant10Webp,
    },
    width: 1920,
    height: 1080,
    views: 1480,
    createdAt: "2024-08-15",
  },
  {
    id: 110,
    title: "Spa 11",
    category: "Spa",
    tags: ["business", "terraza", "familia", "romantico"],
    src: {
      type: "image",
      jpg: assets.spa11,
      webp: assets.spa11Webp,
    },
    width: 1024,
    height: 768,
    views: 633,
    createdAt: "2024-08-20",
  },
  {
    id: 111,
    title: "Habitaciones 12",
    category: "Habitaciones",
    tags: ["pet-friendly", "aventura", "terraza"],
    src: {
      type: "image",
      jpg: assets.rooms12,
      webp: assets.rooms12Webp,
    },
    width: 1600,
    height: 1200,
    views: 754,
    createdAt: "2024-08-25",
  },
  {
    id: 112,
    title: "Habitaciones 13",
    category: "Habitaciones",
    tags: ["vista mar", "romantico"],
    src: {
      type: "image",
      jpg: assets.rooms13,
      webp: assets.rooms13Webp,
    },
    width: 1080,
    height: 1350,
    views: 924,
    createdAt: "2024-08-30",
  },
  {
    id: 113,
    title: "Experiencias 14",
    category: "Experiencias",
    tags: ["business", "eco"],
    src: {
      type: "image",
      jpg: assets.experience14,
      webp: assets.experience14Webp,
    },
    width: 1600,
    height: 1200,
    views: 1609,
    createdAt: "2024-09-04",
  },
  {
    id: 114,
    title: "Habitaciones 15",
    category: "Habitaciones",
    tags: ["business", "gastronomía", "cultura", "romantico"],
    src: {
      type: "image",
      jpg: assets.rooms15,
      webp: assets.rooms15Webp,
    },
    width: 1080,
    height: 1350,
    views: 1085,
    createdAt: "2024-09-09",
  },
  {
    id: 115,
    title: "Restaurante 16",
    category: "Restaurante",
    tags: ["vista mar", "terraza", "pet-friendly"],
    src: {
      type: "image",
      jpg: assets.restaurant16,
      webp: assets.restaurant16Webp,
    },
    width: 1600,
    height: 1200,
    views: 1278,
    createdAt: "2024-09-14",
  },
  {
    id: 116,
    title: "Destino 17",
    category: "Destino",
    tags: ["wellness", "romantico"],
    src: {
      type: "image",
      jpg: assets.destination17,
      webp: assets.destination17Webp,
    },
    width: 1600,
    height: 1200,
    views: 1300,
    createdAt: "2024-09-19",
  },
  {
    id: 117,
    title: "Spa 18",
    category: "Spa",
    tags: ["vista mar", "gastronomía", "pet-friendly", "business"],
    src: {
      type: "video",
      mp4: assets.spa18Video,
      poster: assets.spa18Webp,
    },
    width: 1200,
    height: 1600,
    views: 333,
    createdAt: "2024-09-24",
  },
  {
    id: 118,
    title: "Experiencias 19",
    category: "Experiencias",
    tags: ["cultura", "wellness", "business"],
    src: {
      type: "image",
      jpg: assets.experience19,
      webp: assets.experience19Webp,
    },
    width: 1080,
    height: 1350,
    views: 1444,
    createdAt: "2024-09-29",
  },
  {
    id: 119,
    title: "Destino 20",
    category: "Destino",
    tags: ["cultura", "romantico", "wellness", "familia"],
    src: {
      type: "image",
      jpg: assets.destination20,
      webp: assets.destination20Webp,
    },
    width: 1600,
    height: 1200,
    views: 1967,
    createdAt: "2024-10-04",
  },
  {
    id: 120,
    title: "Spa 21",
    category: "Spa",
    tags: ["cultura", "romantico", "eco"],
    src: {
      type: "image",
      jpg: assets.spa21,
      webp: assets.spa21Webp,
    },
    width: 1080,
    height: 1350,
    views: 744,
    createdAt: "2024-10-09",
  },
  {
    id: 121,
    title: "Habitaciones 22",
    category: "Habitaciones",
    tags: ["gastronomía", "vista mar", "wellness", "premium"],
    src: {
      type: "image",
      jpg: assets.rooms22,
      webp: assets.rooms22Webp,
    },
    width: 1080,
    height: 1350,
    views: 173,
    createdAt: "2024-10-14",
  },
  {
    id: 122,
    title: "Spa 23",
    category: "Spa",
    tags: ["pet-friendly", "gastronomía", "business"],
    src: {
      type: "image",
      jpg: assets.spa23,
      webp: assets.spa23Webp,
    },
    width: 1080,
    height: 1350,
    views: 1497,
    createdAt: "2024-10-19",
  },
  {
    id: 123,
    title: "Spa 24",
    category: "Spa",
    tags: ["business", "vista mar"],
    src: {
      type: "image",
      jpg: assets.spa24,
      webp: assets.spa24Webp,
    },
    width: 1080,
    height: 1350,
    views: 1434,
    createdAt: "2024-10-24",
  },
  {
    id: 124,
    title: "Habitaciones 25",
    category: "Habitaciones",
    tags: ["pet-friendly", "aventura", "romantico"],
    src: {
      type: "video",
      mp4: assets.rooms25Video,
      poster: assets.rooms25Webp,
    },
    width: 1920,
    height: 1080,
    views: 1263,
    createdAt: "2024-10-29",
  },
  {
    id: 125,
    title: "Destino 26",
    category: "Destino",
    tags: ["gastronomía", "premium"],
    src: {
      type: "image",
      jpg: assets.destination26,
      webp: assets.destination26Webp,
    },
    width: 1920,
    height: 1080,
    views: 690,
    createdAt: "2024-11-03",
  },
  {
    id: 126,
    title: "Spa 27",
    category: "Spa",
    tags: ["romantico", "wellness", "terraza"],
    src: {
      type: "image",
      jpg: assets.spa27,
      webp: assets.spa27Webp,
    },
    width: 1024,
    height: 768,
    views: 1631,
    createdAt: "2024-11-08",
  },
  {
    id: 127,
    title: "Habitaciones 28",
    category: "Habitaciones",
    tags: ["eco", "premium", "romantico", "cultura"],
    src: {
      type: "image",
      jpg: assets.rooms28,
      webp: assets.rooms28Webp,
    },
    width: 1024,
    height: 768,
    views: 505,
    createdAt: "2024-11-13",
  },
];
